# Generated by Django 5.2.4 on 2025-10-10 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_add_gallery_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title/caption for the video",
                        max_length=200,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="The actual video file (MP4, MOV, AVI, etc.)",
                        upload_to="gallery/videos/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Cloudinary URL for the video"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Custom thumbnail for the video preview",
                        null=True,
                        upload_to="gallery/video_thumbnails/",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="Cloudinary URL for the video thumbnail"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Video duration (auto-detected when possible)",
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this video should be visible to the public",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display within the folder"
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Who uploaded this video",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="Which folder this video belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="app.galleryfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Video",
                "verbose_name_plural": "Gallery Videos",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
