# Generated by Django 5.2.4 on 2025-08-14 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimonial_remove_financialcheckbook_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcheckbook',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c95a8532-1459-44d3-be70-54a5071e0728'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='minuites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ef38dd9-123b-45f6-8bbf-6b35e406eabe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
