# Generated by Django 5.2.4 on 2025-10-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_galleryvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary URL for the testimonial image",
                null=True,
            ),
        ),
    ]
