# Generated by Django 5.2.4 on 2025-10-19 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_testimonial_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembersGalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Member's name", max_length=200)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Optional description", max_length=255
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Member photo", upload_to="members_gallery/images/"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Cloudinary URL for the image"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for accessibility",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this image should be visible to the public",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display"
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True, help_text="Who uploaded this image", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Member Gallery Image",
                "verbose_name_plural": "Member Gallery Images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
