# Generated by Django 5.2.4 on 2025-08-17 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_financialcheckbook_id_alter_minuites_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcheckbook',
            name='checkbook_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the checkbook file'),
        ),
        migrations.AddField(
            model_name='minuites',
            name='minuites_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the minutes file'),
        ),
        migrations.AlterField(
            model_name='financialcheckbook',
            name='checkbook',
            field=models.FileField(blank=True, null=True, upload_to='checkbooks/'),
        ),
        migrations.AlterField(
            model_name='financialcheckbook',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a95c2f45-06b5-40ea-a8c6-e8bd97014d3a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='minuites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79716a00-65fb-48ef-b977-14e275a63246'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='minuites',
            name='minuites',
            field=models.FileField(blank=True, null=True, upload_to='minuites/'),
        ),
    ]
