# Generated by Django 5.2.4 on 2025-10-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_membersgalleryimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membersgalleryimage",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Member Gallery",
                "verbose_name_plural": "Member Gallery",
            },
        ),
    ]
