# Generated by Django 5.2.4 on 2025-08-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.URLField(help_text='URL of the image (Cloudinary URL)', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.URLField(blank=True, help_text='URL of the featured image (Cloudinary URL)', max_length=500, null=True),
        ),
    ]
