# Generated by Django 5.2.4 on 2025-08-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogimage_image_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the image (Cloudinary URL)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='URL of the featured image (Cloudinary URL)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(help_text='Image file', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image file', null=True, upload_to='blog/featured/'),
        ),
    ]
